### ISSUE TITLE
Option to export all tables

### ISSUE THREAD

**Issue by orlp** [moepmoep12/exile-db#1]
I'd love it if there was an option that simply exports all tables it can. Right now this is quite painful, having to open the schema, read all table names, then filter those names that would error, etc...

I don't really care about minimizing the size of the resulting sqlite database. It's very annoying to realize you want some info from another table, and having to run the export again with a new table, etc. I just want all data in one go.

**Comment by orlp** [comment]
I wrote this for now, skipping the currently bugged/missing tables:

```python
import requests
import json

load_errors = requests.get("https://raw.githubusercontent.com/moepmoep12/exile-db/main/docs/loadErrors.json").json()
build_errors = requests.get("https://raw.githubusercontent.com/moepmoep12/exile-db/main/docs/buildErrors.json").json()
schema = requests.get("https://github.com/poe-tool-dev/dat-schema/releases/download/latest/schema.min.json").json()
other_errors = {"ArchnemesisMods", "CoreLeagues", "DropPool", "Hideouts", "ItemClasses",
        "ItemCostPerLevel", "LeagueFlag", "LegionChests", "MiscAnimated", "Music",
        "ReminderText", "SafehouseCraftingSpree", "SkillGems", "WorldAreas"}

table_names = {t["name"] for t in schema["tables"]} - load_errors.keys() - build_errors.keys() - other_errors
config = { "database": "./poe.sqlite", "tables": sorted(table_names) }

with open("poedb.config.json", "w") as f:
    json.dump(config, f)
```

This is super error prone and manual though. Easiest would be to export all and simply output a log of which tables failed to export, and why.

**Comment by moepmoep12** [comment]
Hello,

I will look into this.

**Comment by moepmoep12** [comment]
Quick solution: Copy `/node_modules/exile-db/poedb.db` to your path of choice, e.g. `/myapp/poedb.sqlite`. The database already contains all valid tables. Then, load each table.


```
const db = new PoEDB("./poedb.sqlite");
const tables = await db.introspection.getTables();
for (const table of tables) {
  try {
    await db.tryLoadTable(table.name as keyof Schema.DB);
  } catch (error) {
    console.log(`Error loading table `, table);
    // remove table or something
  }
}
```

With the new version (release soon) I could load all tables successfully.

**Comment by moepmoep12** [comment]
In version 5.0 the specifier `*` can be used to load all available tables.
For example, `exile-db load --tables * --languages English German --database ./mydb.db`
